### ISSUE TITLE
400: The resource submitted could not be validated.

### ISSUE THREAD

**Issue by websmyth** [edalzell/statamic-mailchimp#26]
I’ve connected a formset to MailChimp but logbook is showing the following error on submission:

`400: The resource submitted could not be validated. For field-specific details, see the 'errors' array.`

The issue only appears when I add the formset to MailChimp (under Form on the settings page), and emails aren’t passed to the corresponding mailing list.

I’ve tried removing the validation from the formset, but that didn’t work.

## Formset

```title: 'Mailing List'
store: false
honeypot: email_address
fields:
  user_email:
    display: Email
    validate: email|required
columns:
  - user_email
```

**Comment by edalzell** [comment]
I bet it's because it assumes the email field is `email`

**Comment by websmyth** [comment]
Thanks, Erin. I’ve changed the formset (and corresponding inputs etc) to:

```title: 'Mailing List'
store: false
honeypot: email_address
fields:
  email:
    display: Email
    validate: email|required
columns:
  - email```

The error has changed to `400: Your merge fields were invalid.`

I haven’t set merge fields as there’s only one and it looks from the docs that email is assumed and auto-merged. I’ve also tried adding merge fields and it’s the same result.

Any ideas? Seems odd.

**Comment by edalzell** [comment]
Let's see your `mailchimp.yaml`

**Comment by websmyth** [comment]
```
mailchimp_key: *************************
add_new_users: true
user_disable_opt_in: false
user_check_permission: false
user_mailchimp_list_id: ************
forms:
  -
    mailchimp_list_id: *************
    disable_opt_in: false
    form: mailing_list
    check_permission: false
```
